Update en.json
FlameOut-Discord/flameout-translate pull request #1
Opened 2021-12-15 21:44 UTC by sprdev

2021-12-15 21:48 UTC, RedGuys requested changes
Надо бы кавычки подправить, а так, вроде норм.

2021-12-15 21:48 UTC, RedGuys commented on en.json
> +      "maxstavka": "maximum bet of `%s' coins.",
Кавычка кривая

2021-12-15 21:48 UTC, RedGuys commented on en.json
> +      "newnumberofcard": "The future number of your card is '%s`, are you ready to buy it for `%s' coins?",
Кавычка кривая

2021-12-16 13:06 UTC, Nubovik01 requested changes
Кавычечки

2021-12-16 13:07 UTC, Nubovik01 requested changes
😭

2021-12-16 13:22 UTC, RedGuys requested changes

2021-12-16 13:22 UTC, RedGuys commented on en.json
> +      "victimnosnus2": "he doesn't have `%s` snus :(",
В оригинале кавычек не было, @Nubovik01 оставляем?

2021-12-16 15:43 UTC, Nubovik01 requested changes
sus

2021-12-16 15:43 UTC, Nubovik01 commented on en.json
> +      "maxstavka": "maximum bet of `%s' coins.",
Хм...

2021-12-16 15:43 UTC, merged